<?php
	$helper = $this->helper('Netbaseteam\Locator\Helper\Data');
?>
<script type="text/javascript">
	require([
		'Cmsmart_Admin_Map'
		    ], function(){		
	});
</script>

<script src="//maps.google.com/maps/api/js?key=<?php echo $helper->getGeoMapApiKey(); ?>&libraries=places" async defer type="text/javascript"
></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/markerclustererplus/2.1.4/markerclusterer.min.js" type="text/javascript" ></script>