<?php
	$helper = $this->helper('Netbaseteam\Locator\Helper\Data');
	
?>
<div class="map-box-container col-sm-8 col-xs-12 pull-right">
	<div id="map-canvas" class="googlemap">
		
	</div>

	<div id="pano"></div>
</div>

<script type="text/javascript">
	require([
		'Cmsmart_Localtor'
		    ], function(){
			    
				
		    });
</script>

<script src="//maps.google.com/maps/api/js?key=<?php echo $helper->getGeoMapApiKey(); ?>&libraries=places" async defer type="text/javascript"
></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/markerclustererplus/2.1.4/markerclusterer.min.js" type="text/javascript" ></script>
