<?php $helper = $this->helper('Netbaseteam\Locator\Helper\Data'); ?>
<div class="map-box-container col-md-8 col-sm-12 col-xs-12 pull-right" id="map-canvas">
	
</div>

<script type="text/javascript">
	
	require([
		'Cmsmart_Store'
		    ], 
		function(){});
</script>

<script src="//maps.google.com/maps/api/js?key=<?php echo $helper->getGeoMapApiKey(); ?>&libraries=places" async defer type="text/javascript"
></script>

<script src="//cdnjs.cloudflare.com/ajax/libs/markerclustererplus/2.1.4/markerclusterer.min.js" type="text/javascript" ></script>
