<?php
    $helper = $this->helper('Netbaseteam\Locator\Helper\Data');
?>
<div class="map-box-container col-lg-6 col-md-12 pull-left">
    <div id="map-canvas" class="googlemap"></div>

    <div id="pano"></div>
</div>

<script type="text/javascript">
    require([
        'Simmons_StoreLocator/js/cmsmart_localtor'
        ], function() {

        }
    );
</script>

<script src="//maps.google.com/maps/api/js?key=<?php echo $helper->getGeoMapApiKey(); ?>&libraries=places,geometry" async defer type="text/javascript"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/markerclustererplus/2.1.4/markerclusterer.min.js" type="text/javascript" ></script>
